#!/bin/bash
# Seed + bascule d'états pour la recette wizard (base ligueenc_recette UNIQUEMENT).
# Usage : ./seed-state.sh init | etape4 | etape3 | etape5 | etape2 | status | cleanup
set -euo pipefail

SQL() { docker exec -i ligue-recette-mysql mysql -urecette -precette2026 ligueenc_recette -e "$1"; }

case "${1:-status}" in
  init)
    SQL "
    INSERT INTO SEASON (LABEL, STATUS, IS_CURRENT) VALUES
      ('TEST-CLOSED-2025','CLOSED',0),
      ('TEST-SETUP-2027','SETUP',0),
      ('TEST-SETUP-SANSLIGUE','SETUP',0),
      ('TEST-SETUP-VIDE','SETUP',0);
    SET @sA=(SELECT ID_SEASON FROM SEASON WHERE LABEL='TEST-CLOSED-2025');
    SET @sB=(SELECT ID_SEASON FROM SEASON WHERE LABEL='TEST-SETUP-2027');
    SET @sC=(SELECT ID_SEASON FROM SEASON WHERE LABEL='TEST-SETUP-SANSLIGUE');
    INSERT INTO LEAGUE (ID_CHIEF, ID_FORUM, NAME, FIRST_YEAR, ID_SEASON, DIVISION_LABEL, TIER) VALUES
      (0,0,'TEST Division Fermée 1',2025,@sA,'TDF1',1),
      (0,0,'TEST Division Fermée 2',2025,@sA,'TDF2',2),
      (0,0,'TEST Ligue A',2027,@sB,'TLA',1),
      (0,0,'TEST Ligue B',2027,@sB,'TLB',2),
      (0,0,'TEST Ligue C',2027,@sB,'TLC',3);
    INSERT INTO LEAGUE_USER (ID_LEAGUE, ID_USER)
      SELECT ID_LEAGUE, 1461 FROM LEAGUE WHERE NAME='TEST Division Fermée 1';
    INSERT INTO LEAGUE_USER (ID_LEAGUE, ID_USER)
      SELECT ID_LEAGUE, 1462 FROM LEAGUE WHERE NAME='TEST Division Fermée 2';
    INSERT INTO LEAGUE_USER (ID_LEAGUE, ID_USER)
      SELECT ID_LEAGUE, 1461 FROM LEAGUE WHERE NAME='TEST Ligue A';
    INSERT INTO LEAGUE_USER (ID_LEAGUE, ID_USER)
      SELECT ID_LEAGUE, 1462 FROM LEAGUE WHERE NAME='TEST Ligue B';
    INSERT INTO LEAGUE_USER (ID_LEAGUE, ID_USER)
      SELECT ID_LEAGUE, 1463 FROM LEAGUE WHERE NAME='TEST Ligue C';
    INSERT INTO CLUB (ID_CLUB_EQ, NAME, ID_SEASON) VALUES
      ('TSTA','TEST Club Alpha',@sB), ('TSTB','TEST Club Beta',@sB), ('TSTC','TEST Club Gamma',@sC);
    INSERT INTO PLAYER (FNAME, LNAME, POSITION, ID_CLUB, ID_SEASON)
      SELECT 'Gard','Alpha','Gardien',ID_CLUB,@sB FROM CLUB WHERE NAME='TEST Club Alpha' UNION ALL
      SELECT 'Def','Alpha','Défense',ID_CLUB,@sB FROM CLUB WHERE NAME='TEST Club Alpha' UNION ALL
      SELECT 'Mil','Alpha','Milieu',ID_CLUB,@sB FROM CLUB WHERE NAME='TEST Club Alpha' UNION ALL
      SELECT 'Gard','Beta','Gardien',ID_CLUB,@sB FROM CLUB WHERE NAME='TEST Club Beta' UNION ALL
      SELECT 'Att','Beta','Attaque',ID_CLUB,@sB FROM CLUB WHERE NAME='TEST Club Beta' UNION ALL
      SELECT 'Def','Gamma','Défense',ID_CLUB,@sC FROM CLUB WHERE NAME='TEST Club Gamma';
    "
    echo "seed init OK"
    ;;
  etape4)
    SQL "UPDATE SEASON SET STATUS='SETUP'  WHERE LABEL='TEST-SETUP-2027';
         UPDATE SEASON SET STATUS='CLOSED' WHERE LABEL IN ('TEST-SETUP-SANSLIGUE','TEST-SETUP-VIDE');"
    echo "état etape4 (TEST-SETUP-2027 en SETUP)"
    ;;
  etape3)
    SQL "UPDATE SEASON SET STATUS='SETUP'  WHERE LABEL='TEST-SETUP-SANSLIGUE';
         UPDATE SEASON SET STATUS='CLOSED' WHERE LABEL IN ('TEST-SETUP-2027','TEST-SETUP-VIDE');"
    echo "état etape3 (TEST-SETUP-SANSLIGUE en SETUP)"
    ;;
  etape5)
    SQL "UPDATE SEASON SET STATUS='AUCTION' WHERE LABEL='TEST-SETUP-2027';
         UPDATE SEASON SET STATUS='CLOSED'  WHERE LABEL IN ('TEST-SETUP-SANSLIGUE','TEST-SETUP-VIDE');"
    echo "état etape5 (TEST-SETUP-2027 en AUCTION)"
    ;;
  etape2)
    SQL "UPDATE SEASON SET STATUS='SETUP'  WHERE LABEL='TEST-SETUP-VIDE';
         UPDATE SEASON SET STATUS='CLOSED' WHERE LABEL IN ('TEST-SETUP-2027','TEST-SETUP-SANSLIGUE');"
    echo "état etape2 (TEST-SETUP-VIDE en SETUP)"
    ;;
  status)
    SQL "SELECT ID_SEASON, LABEL, STATUS, IS_CURRENT FROM SEASON ORDER BY ID_SEASON;"
    ;;
  cleanup)
    SQL "
    SET @ids=(SELECT GROUP_CONCAT(ID_SEASON) FROM SEASON WHERE LABEL LIKE 'TEST-%');
    DELETE lu FROM LEAGUE_USER lu JOIN LEAGUE l ON lu.ID_LEAGUE=l.ID_LEAGUE
      WHERE FIND_IN_SET(l.ID_SEASON, @ids);
    DELETE FROM LEAGUE  WHERE FIND_IN_SET(ID_SEASON, @ids);
    DELETE FROM PLAYER  WHERE FIND_IN_SET(ID_SEASON, @ids);
    DELETE FROM CLUB    WHERE FIND_IN_SET(ID_SEASON, @ids);
    DELETE FROM SEASON  WHERE LABEL LIKE 'TEST-%';
    "
    echo "cleanup OK"
    ;;
  *) echo "usage: $0 init|etape4|etape3|etape5|etape2|status|cleanup"; exit 1 ;;
esac
